### PR TITLE
Implement From<BackendError> for Error

### PR DESCRIPTION
**Pull request by ramyak-mehra**
Signed-off-by: Ramyak Mehra <rmehra_be19@thapar.edu>

### Summary of the PR
Implements From for BackednError and JsonFrontentError for Erro in lib.rs and replaced map_err wherever neccessary

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.

### CODE REVIEW

**Comment by ramyak-mehra** [comment]
> Looks good, thanks for the contribution.
> In order to have the tests pass, either lower the coverage to the reported value or add some tests that perform the simple casts. That's fine by me either way, since the added code simple enough.

I don't see a need to write test for these. I just wanted to know are there any other place should I make similar changes, or add these changes for any other error?

**Comment by alindima** [comment]
> > Looks good, thanks for the contribution.
> > In order to have the tests pass, either lower the coverage to the reported value or add some tests that perform the simple casts. That's fine by me either way, since the added code simple enough.
> 
> I don't see a need to write test for these. I just wanted to know are there any other place should I make similar changes, or add these changes for any other error?

I don't see another place that needs changes. @andreeaflorescu @petreeftime WDYT? The other changes should be made by applications consuming seccompiler (but not neccessarily, as it's not a breaking change). In that case, you may just update the coverage in `coverage_config_x86_64.json` with the new value.

**Review by alindima — APPROVED** [review]

**Comment by alindima** [comment]
Please make sure to add a Signed-off-by line to the second commit

**Review by andreeaflorescu — APPROVED** [review]

**Comment by andreeaflorescu** [comment]
I would suggest to also add `Fixes: #38` to the commit message so that the issue is automatically closed when the PR is merged. This is optional, and you can do it for your future PRs.

**Review by alindima — APPROVED** [review]

**Pull request merged**
